name: Publish GitHub Pages

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        required: false
        default: ubuntu-latest

permissions:
  contents: write
  pages: write

jobs:
  build-and-publish:
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js version from package.json
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline --ignore-scripts

      - name: Build
        run: npm run build

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
